ifnti_l3/ifnti_l3/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('notes/',include('notes.urls')),
]

ifnti_l3/notes/urls.py
from django.urls import path 
from . import views
app_name = 'notes'

urlpatterns = [
    path('',views.index, name = 'index'),
    path('eleves',views.eleves,name='eleves'),
    path('eleves/<id>',views.eleve,name='eleves'),
    path('matieres', views.matieres,name='matieres'),
    path('matieres/<id>',views.matiere, name='matieres'),
    path('niveau/<id>',views.niveau,name='niveau'),

    path('add_note/<int:matiere_id>/<int:eleve_id>',views.add_note, name = 'add_note'),
    
]

ifnti_l3/notes/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils.text import slugify
from django.utils import timezone
# Create your models here.
class Personne(models.Model):
    id = models.BigAutoField(primary_key=True)
    nom = models.CharField(max_length=50)
    prenom = models.CharField(max_length=50)
    sexe = models.CharField(max_length=1,
    choices=[("M", "Masculin"), ("F", "Féminin")])
    date_naissance = models.DateField(null=True)
    class Meta:
        abstract = True
    def __str__(self) -> str:
        return self.nom
class Enseignant(Personne):
    pass
class Meta:
    verbose_name = 'Enseignant'
    verbose_name_plural = 'Enseignant'
    def __str__(self) -> str:
        return super().__str__()
    
class Niveau(models.Model):
    nom = models.CharField(unique=True,max_length=2,null=True)
    class Meta:
        verbose_name = 'Niveau'
        verbose_name_plural = 'Niveau'
    def __str__(self) -> str:
        return self.nom 

class Matiere(models.Model):
    nom = models.CharField(unique=True,max_length=50)
    enseignant = models.ForeignKey(Enseignant,on_delete=models.SET_NULL,null=True)
    niveaux = models.ManyToManyField(Niveau)
    class Meta:
        verbose_name = 'Matière'
        verbose_name_plural = 'Matière'
    def __str__(self) -> str:
        return self.nom 
    
class Eleve(Personne):
    eleve_id = models.BigIntegerField(unique=True)
    niveau = models.ForeignKey(Niveau,on_delete=models.SET_NULL,null=True)
    matieres = models.ManyToManyField(Matiere)
    class Meta:
        verbose_name = 'Élève'
        verbose_name_plural = 'Élève'
    def __str__(self) -> str:
        return super().__str__()  

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.eleve_id = self.generate_eleve_id(instance)
        if commit:
            instance.save()
        return instance
        def generate_eleve_id(self, instance):
            timestamp = int(timezone.now().timestamp())
            nom_abbrev = slugify(instance.nom)[:2].upper()
            return f"{timestamp}_{nom_abbrev}"  
    
class Note(models.Model):
    valeur = models.FloatField(null=True,validators=[MinValueValidator(0), MaxValueValidator(20)])
    eleve = models.ForeignKey(Eleve,on_delete=models.CASCADE)
    matiere = models.ForeignKey(Matiere,on_delete=models.CASCADE)
    def __str__(self):
        return str(self.valeur)    

ifnti_l3/notes/forms.py
from django.forms import ModelForm
from django.core.validators import MinValueValidator, MaxValueValidator
from notes.models import Note,Eleve


class NoteForm(ModelForm):
    class Meta:
        model = Note
        fields = ["valeur"]
        labels = {"valeur": "Note sur 20"}
        validators = [
            MinValueValidator(0, message="La note doit être supérieure ou égale à 0."),
            MaxValueValidator(20, message="La note doit être inférieure ou égale à 20.")
        ]
class EleveForm(ModelForm):
    class Meta:
        fields = '__all__'
        model = Eleve  

    def clean(self):
        cleaned_data = super().clean()
        nom = cleaned_data.get('nom')
        prenom = cleaned_data.get('prenom')

        if any(char.isdigit() for char in nom):
            self.add_error('nom', 'Le nom ne doit pas contenir de chiffres.')

        if any(char.isdigit() for char in prenom):
            self.add_error('prenom', 'Le prénom ne doit pas contenir de chiffres.')          
            

ifnti_l3/notes/views.py
from django.shortcuts import render,get_object_or_404,redirect

# Create your views here.
from django.http import HttpResponse
from notes.models import Matiere,Enseignant,Eleve,Niveau,Note
from notes.forms import NoteForm
def index(request):
	return render(request, "notes/index.html")

def eleves(request):
	eleves = Eleve.objects.all()
	return render(request,'notes/eleves.html',{'eleves':eleves})


def eleve(request, id):
	eleve = get_object_or_404(Eleve,pk=id)
	matieres = eleve.matieres.all()
	return render(request,'notes/eleve.html',{'eleve':eleve,'matieres':matieres})
	
def matieres(request):
	matieres = Matiere.objects.all()
	return render(request,'notes/matieres.html',{'matieres':matieres})
	

def matiere(request, id):
	matiere = get_object_or_404(Matiere,pk=id)
	return render(request,'notes/matiere.html',{'matiere':matiere})

def niveau(request, id):
	niveau = get_object_or_404(Niveau,pk=id)
	return render(request,'notes/niveau.html',{'niveau':niveau})

def add_note(request, matiere_id, eleve_id):
	matiere = Matiere.objects.get(pk=matiere_id)
	eleve = Eleve.objects.get(pk=eleve_id)

	# if request.method == "POST":
	# 	valeur = request.POST.get("note")
	# 	note = Note(eleve_id=eleve_id, matiere_id=matiere_id,valeur=valeur)
	# 	note.save()
	# 	return redirect("/notes/eleves")
	# else:
	# 	if eleve.matieres.filter(pk=matiere_id).exists():
	# 		return render(request, 'notes/add_note.html', locals())
	# 	else:
	# 		raise ValueError(f"The student ({eleve_id}) is not enrolled in the subject ({matiere_id}).")
	if request.method == "POST":
		form = NoteForm(request.POST)
		if form.is_valid():
			try:
				note = form.save(commit=False)
				note.eleve = eleve
				note.matiere = matiere
				note.save()
				return redirect('/notes/eleves')
			except:
				pass	
		
	
	else:
		form = NoteForm()
		return render(request, 'notes/add_note.html',{"form":form})
	

ifnti_l3/notes/templates/notes/add_note.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Note</title>
    <style>
        form{
            padding: 50px;
        }
        div{
            padding: 20px;
        }
    </style>
</head>
<body>
    <div class="container">
        <form action="" method="post">
            {% csrf_token %}
            <div class="enf">
                <!-- <label for="note">Note</label>
                <input type="number" name="note"> -->
                {{ form.valeur.label_tag }}
                {{form.valeur}}
                {%if form.valeur.errors%}
                <ul>
                    {%for error in form.valeur.errors%}
                        <li>{{ error }}</li>
                    {%endfor%}
                </ul>

                {%endif%}
            </div>
            <button type="submit">Add</button>
        </form>
       
    </div>
</body>
</html>

ifnti_l3/notes/templates/notes/eleve.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Détails eleve</title>
    <style>
        /* *{
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }
        .container{
            text-align: center;
            padding: 50px;
            width: 500px;
            margin: auto;
            background-color: orange;
            margin-top: 20px;
            border: 2px solid yellowgreen;
            border-radius: 10px;
            box-shadow: 3px 6px 8px whitesmoke;
        } */
       
    </style>
</head>
<body>
    <div class="container">
        <h1>Eleve : {{eleve.eleve_id}}</h1>
        <p><strong>Nom: </strong> {{eleve.nom}}</p>
        <p><strong>Prenom: </strong> {{eleve.prenom}}</p>
        <p><strong>Niveau: </strong> {{eleve.niveau}}</p>
        <p><strong>Matières suivies</strong></p>
        <ul>
            {%for mat in matieres%}
            <li><a href="{% url 'notes:add_note' mat.id eleve.id %}">{{ mat.nom }}</a></li>

            {%endfor%}
        </ul>
    </div>
   
</body>


</html>

ifnti_l3/notes/templates/notes/eleves.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Liste eleves</title>
    <style>
        body{
         
          text-align: center;
        }
        a{
           
            color: grey;
        }
        a:hover{
            color: orange;
        }
        h2{
            margin: 50px;
            border: 3px solid green;
            border-radius: 5px;
            width: 35%;
          margin-left: 34%;
        }
        .container{
           margin: auto;
        }
      
    </style>
</head>
<body>
    <div class="container">
        <h2>Nos Éleves</h2>
        <!-- <ul> -->
    
            {% for elev in eleves %}
            <p>
                <a href="{% url 'notes:eleves' %}/{{ elev.id }}"><li>{{ elev.nom }} {{elev.prenom}}</li></a>
            <hr/>
           
            {% endfor %}
        </p>
    </div>
    
</body>
</html>

ifnti_l3/notes/templates/notes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Gestion de Notes</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- Custom styles -->
    <style>
        body {
            background-color: #f8f9fa;
        }

        .container {
            margin-top: 50px;
        }

        .jumbotron {
            background-color: #007bff;
            color: #fff;
            padding: 2rem 1rem;
        }

        h1, h2 {
            color: #007bff;
        }

        .btn-primary {
            background-color: #007bff;
            border-color: #007bff;
        }

        .btn-primary:hover {
            background-color: #0056b3;
            border-color: #0056b3;
        }
    </style>
</head>
<body>

<div class="jumbotron text-center">
    <h1 class="display-4">Gestion de Notes</h1>
    <p class="lead">Une application simple pour gérer les notes des élèves</p>
    <hr class="my-4">
    <p>Commencez dès maintenant</p>
    <a class="btn btn-primary btn-lg" href="#" role="button">Se connecter</a>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2>Fonctionnalité 1</h2>
            <p>Une description concise de la première fonctionnalité.</p>
        </div>
        <div class="col-md-6">
            <h2>Fonctionnalité 2</h2>
            <p>Une description concise de la deuxième fonctionnalité.</p>
        </div>
    </div>
</div>

<!-- Bootstrap JS and dependencies (jQuery, Popper.js) -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

ifnti_l3/notes/templates/notes/matiere.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Détails matiere</title>
</head>
<body>
    <h1>Matière : {{matiere.id}}</h1>
    <p>Désignation : {{matiere.nom}}</p>
    <p>Enseigant responsable : {{matiere.enseignant}}</p>
    <div>
        Niveaux d'ens : 
        {% for niv in matiere.niveaux.all %}
        <span>{{ niv}}</span>
        {%endfor%}
    </div>
</body>
</html>

ifnti_l3/notes/templates/notes/matieres.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Liste matieres</title>
    <style>
      
        h2{
            margin: 20px;
        }
        body{
            text-align: center;
        }
        a{
            color: gray;
        }
        a:hover{
            color: orange;
        }
    </style>
</head>
<body>
    <h2>Nos Matieres</h2>
    <div>
        <!-- {%for mat in matieres%}
        <a href="/notes/matiere/{{mat.id}}"><li>{{mat.nom}} a pour enseignant {{mat.enseignant}}</li></a>
        {%endfor%} -->
        {% for mat in matieres %}
        <p>
             <a href="{% url 'notes:matieres' %}/{{ mat.id }}"><li>{{ mat.nom }}</li></a>
             <hr>
        </p>
           
        {% endfor %}

    </div>
</body>
</html>

ifnti_l3/notes/templates/notes/niveau.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Détails niveau</title>
</head>
<body>
    <h1>niveau : {{niveau.id}}</h1>
    <p>{{niveau.nom}}</p>
    
</body>
</html>